AWSTemplateFormatVersion: 2010-09-09
Description: >-
  SAM template with typescript support

Transform:
  - AWS::Serverless-2016-10-31

Parameters:
  tokenSecret:
    Type: String
    Description: token secret

Globals:
  Function:
    Layers:
      - !Ref RuntimeDependenciesLayer
    Runtime: nodejs18.x
    MemorySize: 128
    Timeout: 100

Resources:
  ServiceAPIGateway:
    Type: AWS::Serverless::Api
    Properties:
      Name: Service api gateway
      StageName: prod
      Cors:
        AllowMethods: "'GET,POST,OPTIONS,PUT,DELETE'"
        AllowHeaders: "'*'"
        AllowOrigin: "'*'"

  Hello:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: makefile
    Properties:
      Handler: dist/handlers/hello.handler
      Description: sample function
      Environment:
        Variables:
          ENDPOINT_URL: ''
      Events:
        Api:
          Type: Api
          Properties:
            RestApiId: !Ref ServiceAPIGateway
            Path: /hello
            Method: GET

  # Shared layer with Lambda runtime dependencies
  RuntimeDependenciesLayer:
    Type: AWS::Serverless::LayerVersion
    Metadata:
      BuildMethod: makefile
    Properties:
      LayerName: "upload-api2-dependencies"
      Description: Runtime dependencies for Lambdas
      ContentUri: ./
      CompatibleRuntimes:
        - nodejs18.x
      RetentionPolicy: Retain

Outputs:
  WebEndpoint:
    Description: "API Gateway endpoint URL for Prod stage"
    Value: !Sub "https://${ServiceAPIGateway}.execute-api.${AWS::Region}.amazonaws.com/prod/"
